[[getting-started]]
== Getting Started

The classic model of how free software projects get started was supplied
by Eric Raymond, in a now-famous paper on open source processes entitled
The Cathedral and the Bazaar. He wrote:

________________________________________________________________________________________________________
_Every good work of software starts by scratching a developer's personal
itch._

(from
**http://www.catb.org/~esr/writings/cathedral-bazaar/[catb.org/~esr/writings/cathedral-bazaar/]**)
________________________________________________________________________________________________________

Note that Raymond wasn't saying that open source projects happen only
when some individual gets an itch. Rather, he was saying that _good_
software results when the programmer has a personal interest in seeing
the problem solved; the relevance of this to free software was that a
personal itch happened to be the most frequent motivation for starting a
free software project.

This is still how most free software projects are started, but less so
now than in 1997, when Raymond wrote those words. Today, we have the
phenomenon of organizations—for-profit corporations, governments,
non-profits, etc—starting large, centrally-conceived open source
projects from scratch. The lone programmer, banging out some code to
solve a local problem and then realizing the result has wider
applicability, is still the source of much new free software, but is not
the only story.

Raymond's point is still insightful, however. The essential condition is
that the producers of the software have a direct interest in its
success, usually because they use it themselves or work directly with
people who use it. If the software doesn't do what it's supposed to do,
the person or organization producing it will feel the dissatisfaction in
their daily work. For example, the open source software developed by the
Kuali Foundation (http://www.kuali.org/[kuali.org]), used by educational
institutions to manage their finances, research grants, HR systems,
student information, etc, can hardly be said to scratch any individual
programmer's personal itch. It scratches an institutional itch. But that
itch arises directly from the experiences of the institutions concerned,
and therefore if the project fails to satisfy them, they will know. This
arrangement produces good software because the feedback loop flows in
the right direction. The program isn't being written to be sold to
someone else so they can solve _their_ problem. It's being written to
solve one's _own_ problem, and then shared with everyone, much as though
the problem were a disease and the software were medicine whose
distribution is meant to completely eradicate the epidemic.

This chapter is about how to introduce a new free software project to
the world, but many of its recommendations would sound familiar to a
health organization distributing medicine. The goals are very similar:
you want to make it clear what the medicine does, get it into the hands
of the right people, and make sure that those who receive it know how to
use it. But with software, you also want to entice some of the
recipients into joining the ongoing research effort to improve the
medicine.

Free software distribution is a twofold task. The software needs to
acquire users, and to acquire developers. These two needs are not
necessarily in conflict, but they do add some complexity to a project's
initial presentation. Some information is useful for both audiences,
some is useful only for one or the other. Both kinds of information
should subscribe to the principle of scaled presentation; that is, the
degree of detail presented at each stage should correspond to the amount
of time and effort put in by the reader at that stage. More effort
should always result in more reward. When the two do not correlate
tightly, people may quickly lose faith and stop investing effort.

The corollary to this is that __appearances matter__. Programmers, in
particular, often don't like to believe this. Their love of substance
over form is almost a point of professional pride. It's no accident that
so many programmers exhibit an antipathy for marketing and public
relations work, nor that professional graphic designers are often
horrified at the designs programmers come up with on their own.

This is a pity, because there are situations where form _is_ substance,
and project presentation is one of them. For example, the very first
thing a visitor learns about a project is what its web site looks like.
This information is absorbed before any of the actual content on the
site is comprehended—before any of the text has been read or links
clicked on. However unjust it may be, people cannot stop themselves from
forming an immediate first impression. The site's appearance signals
whether care was taken in organizing the project's presentation. Humans
have extremely sensitive antennae for detecting the investment of care.
Most of us can tell in one glance whether a web site was thrown together
quickly or was given serious thought. This is the first piece of
information your project puts out, and the impression it creates will
carry over to the rest of the project by association.

Thus, while much of this chapter talks about the content your project
should start out with, remember that its look and feel matter too.
Because the project web site has to work for two different types of
visitors—users and developers—special attention must be paid to clarity
and directedness. Although this is not the place for a general treatise
on web design, one principle is important enough to deserve mention,
particularly when the site serves multiple (if overlapping) audiences:
people should have a rough idea where a link goes before clicking on it.
For example, it should be obvious _from looking at the links_ to user
documentation that they lead to user documentation, and not to, say,
developer documentation. Running a project is partly about supplying
information, but it's also about supplying comfort. The mere presence of
certain standard offerings, in expected places, reassures users and
developers who are deciding whether they want to get involved. It says
that this project has its act together, has anticipated the questions
people will ask, and has made an effort to answer them in a way that
requires minimal exertion on the part of the asker. By giving off this
aura of preparedness, the project sends out a message: "Your time will
not be wasted if you get involved," which is exactly what people need to
hear.

If you use a "canned hosting" site (see
<<canned-hosting>>), one advantage of that
choice is that those sites have a default layout that is similar from
project to project, and is pretty well-suited to presenting a project to
the world. That layout can be customized, within certain boundaries, but
the default design prompts you to include the information visitors are
most likely to be looking for.

include::sections/look-around-first.adoc[But First, Look Around]

include::sections/starting-from-what-you-have.adoc[Starting From What You Have]

include::sections/choosing-a-name.adoc[Choose a Good Name]

include::sections/own-the-name.adoc[Own the name in the important namespaces]

include::sections/mission-statement.adoc[Have a Clear Mission Statement]

include::sections/state-freedom.adoc[State That the Project is Free]

include::sections/features-and-requirements.adoc[Features and Requirements List]

include::sections/development-status.adoc[Development Status]

include::sections/downloads.adoc[Downloads]

include::sections/vc-and-bug-tracker-access.adoc[Version Control and Bug Tracker Access]

include::sections/communications-channels.adoc[Communications Channels]

include::sections/developer-guidelines.adoc[Developer Guidelines]

include::sections/documentation.adoc[Documentation]

include::sections/examples-and-demos.adoc[Demos, Screenshots, Videos, and Example Output]

include::sections/hosting.adoc[Hosting]

include::sections/license-quickstart.adoc[Choosing a License and Applying It]

include::sections/setting-tone.adoc[Setting the Tone]

include::sections/announcing.adoc[Announcing]
