[[sources]]
=== Sources

Much of the raw material for the first edition of this book came from
five years of working with the Subversion project
(http://subversion.tigris.org/[subversion.tigris.org]). Subversion is an
open source version control system, written from scratch, and intended
to replace CVS as the _de facto_ version control system of choice in the
open source community. The project was started by my employer, CollabNet
(http://www.collab.net/[collab.net]), in early 2000, and thank goodness
CollabNet understood right from the start how to run it as a truly
collaborative, distributed effort. We got a lot of volunteer developer
buy-in early on; today there are 50-some developers on the project, of
whom only a few are CollabNet employees.

Subversion is in many ways a classic example of an open source project,
and I ended up drawing on it more heavily than I originally expected.
This was partly a matter of convenience: whenever I needed an example of
a particular phenomenon, I could usually call one up from Subversion
right off the top of my head. But it was also a matter of verification.
Although I am involved in other free software projects to varying
degrees, and talk to friends and acquaintances involved in many more,
one quickly realizes when writing for print that all assertions need to
be fact-checked. I didn't want to make statements about events in other
projects based only on what I could read in their public mailing list
archives. If someone were to try that with Subversion, I knew, she'd be
right about half the time and wrong the other half. So when drawing
inspiration or examples from a project with which I didn't have direct
experience, I tried to first talk to an informant there, someone I could
trust to explain what was really going on.

While Subversion was my full time job from 2000-2006, I've been involved
in free software for more than twenty years, including the seven years
since 2006 (when the first edition of this book was published). Other
projects and organizations that have influenced this book include:

* The GNU Emacs text editor project at the Free Software Foundation, in
which I maintain a few small packages.
* Concurrent Versions System (CVS), which I worked on intensely in
1994–1995 with Jim Blandy and was involved with intermittently for a few
years afterwards.
* The collection of open source projects known as the Apache Software
Foundation, especially the Apache Portable Runtime (APR) and Apache HTTP
Server.
* The Launchpad.net project at Canonical, Ltd.
* Code for America and O'Reilly Media, which gave me an inside view on
open source civic technology development starting in 2010, and kindly
kept me in the loop after I became a full-time independent consultant in
2012.
* The many open source anti-surveillance and censorship-circumvention
tools supported by the Open Internet Tools Project (OpenITP.org) and by
the Open Technology Institute at the New America Foundation.
* Checkbook NYC, the municipal financial transparency software released
by the New York City Office of the Comptroller.
* The Arches Project, an open source geospatial web application for
inventorying and helping protect cultural heritage sites (e.g., historic
buildings, archeological sites, etc), created by the Getty Conservation
Institute and World Monuments Fund.
* OpenOffice.org / LibreOffice.org, the Berkeley Database from
Sleepycat, and MySQL Database; I have not been involved with these
projects personally, but have observed them and, in some cases, talked
to people there.
* GNU Debugger (GDB) (likewise).
* The Debian Project (likewise).

This is not a complete list, of course. Like most open source
programmers, I also keep loose tabs on many different projects of
interest to me, just to have a sense of the general state of things. I
won't name all of them here, but they are mentioned in the text where
appropriate.
