[[why]]
=== Why Write This Book?

At parties, people no longer give me a blank stare when I tell them I
write free software. "Oh, yes, open source—like Linux?" they say. I nod
eagerly in agreement. "Yes, exactly! That's what I do." It's nice not to
be completely fringe anymore. In the past, the next question was usually
fairly predictable: "How do you make money doing that?" To answer, I'd
summarize the economics of open source: that there are organizations in
whose interest it is to have certain software exist, but that they don't
need to sell copies, they just want to make sure the software is
available and maintained, as a tool instead of as a commodity.

The next question is not always about money, though. The business case
for open source softwarefootnote:[The terms "open source software" and
"free software" are essentially synonymous in this context; they are
discussed more in <<free-vs-open-source>> in
<<introduction>>.] is no longer so mysterious, and even
non-programmers already understand—or at least are not surprised—that
there are people employed at it full time. Instead, the next question is
often "__Oh, how does that work?__"

I didn't have a satisfactory answer ready, and the harder I tried to
come up with one, the more I realized how complex a topic it really is.
Running a free software project is not exactly like running a business
(imagine having to constantly negotiate the nature of your product with
a group of volunteers, most of whom you've never met!). Nor, for various
reasons, is it exactly like running a traditional non-profit
organization, nor a government. It has similarities to all these things,
but I have slowly come to the conclusion that free software is __sui
generis__. There are many things with which it can be usefully compared,
but none with which it can be equated. Indeed, even the assumption that
free software projects can be "run" is a stretch. A free software
project can be __started__, and it can be influenced by interested
parties, often quite strongly. But its assets cannot be made the
property of any single owner, and as long as there are people
somewhere—anywhere—interested in continuing it, it cannot be
unilaterally shut down. Everyone has infinite power; everyone has no
power. It's an interesting dynamic.

That is why I wanted to write this book in the first place, and seven
years later, wanted to update it. Free software projects have evolved a
distinct culture, an ethos in which the liberty to make the software do
anything one wants is a central tenet. Yet the result of this liberty is
not a scattering of individuals each going their own separate way with
the code, but enthusiastic collaboration. Indeed, competence at
cooperation itself is one of the most highly valued skills in free
software. To manage these projects is to engage in a kind of
hypertrophied cooperation, where one's ability not only to work with
others but to come up with new ways of working together can result in
tangible benefits to the software. This book attempts to describe the
techniques by which this may be done. It is by no means complete, but it
is at least a beginning.

Good free software is a worthy goal in itself, and I hope that readers
who come looking for ways to achieve it will be satisfied with what they
find here. But beyond that I also hope to convey something of the sheer
pleasure to be had from working with a motivated team of open source
developers, and from interacting with users in the wonderfully direct
way that open source encourages. Participating in a successful free
software project is a deep pleasure, and ultimately that's what keeps
the whole system going.
