= Producing Open Source Software: How to Run a Successful Free Software Project

_Status: This is an exploratory fork of the excellent book
link:http://producingoss.com[Producing Open Source Software]. It currently is
not much to look at. Check out link:book.adoc[] to see the latest content, and
link:CONTRIBUTING.adoc[] for more information on how to get involved._

== About this fork

While the excellent book link:http://producingoss.com[Producing Open Source
Software] has long been the most complete resource for creating open source
software projects, the book format does not lend itself to the rapidly maturing
and adapting world of open source software. The format requires brief periods of
intense work by one individual, followed by long periods of decay.

This fork intends to be an ever evolving resource with the following goals:

- It will be optimized for viewing on the web while continuing to be consumable
  in book form.

- It will be an opinionated resource that reflects the practices of modern open
  source communities and will likely exclude details that are not applicable to
  most communities.

- It will be run as an open source project, with community contributions
  accepted and encouraged.

See the link:CHANGELOG.adoc[] for significant changes to this fork.
