     Oh Most Noble and Gracious Emacs, please be in -*- org -*- mode!

This is where pending todo items for the 2nd edition live.

If something you expected to see here is missing, the omission may not
be intentional, or that may be one of the todo items kept in a private
file (because it comes from a confidential suggestion -- the result
will be public, but the information leading to the result is private).
See also the notes.org file, which contains ideas and notes and stuff
that may be actionable some day but that I don't consider to be "todo"
items right now.

* Content ideas
** From Kit Plummer
   From: Kit Plummer
   Subject: Re: [mil-oss] November mil-oss Book Club
   To: mil-oss
   Date: Mon, 5 Nov 2012 07:32:09 -0700
    
   Very cool Karl.  On the topic of [1] I hope that the intent is to
   discuss the value of DVCS and not necessarily Github specifically.
    
   When I first read the book (back in '05), the biggest challenge for me
   wasn't the tactics of running an open source project, but the
   complexities associated with cultural requirements at executive,
   project management and engineering levels.  I'd love to see a section
   in "Setting the Tone" identify with this a bit.  I know you've covered
   well the "change" as it affects developers…
    
   Thanks.
   Kit
** Supporting drive-by contributors.
   E.g., the [Re: (0 <= i && i < N) is not "backwards"] thread on emacs-devel,
   started by Paul Eggert on 24 (?) March 2013.
**** Also relevant as a bikeshed example!
** Inner-sourcing, "community source", and other half-source things
   Inner sourcing isn't really like open source: the actors are
   ultimately all part of the same hierarchical authority structure, so
   true permissionless initiative is hard to achieve, and it also fails
   the "portable résumé" test -- you can't take the code with you, so
   you can still be alienated from your work, so some of the motivation
   to invest personally is gone.
** How to handle the worry about offering infinite support
   Many orgs (esp non-profits and gov't customers and their
   contractors) worry about the degree to which they might be required
   to engage & meet expectations of third parties, e.g., in responding
   to questions in public forums, in meeting roadmap deadlines, feature
   goals, etc.  This is especially true when the project is open source
   from the start.  Answer is to clearly define & agree on what
   obligations are: paying customers come first, and then make a
   conscious choice about controlling the other costs.
 
   Explicitly follow up in public forums to say "We're heads-down
   working on features right now [or whatever], but there was this
   thread from so-and-so a few months ago that might have an answer.
   [link] So-and-so, do you have anything to add?"  over to community
   experts.

   "You open source your code, not your time and attention."

   (But see reference in notes.org to Koen van Daele's email 
   "Re: Arches" in Aug/Sep 2012, for an argument the other way.)
** Do a general link check.
*** Check where http:// URLs can be https://, use the latter where possible.
*** CDT spam report dead link bug filed (for link in Chapter 3).
    Latest update: they're supposed to let me know whether the link can
    now be relied on (see thread in "cdt" mail folder).
   
    Filed this via https://www.cdt.org/contact on [2013-12-18]:
 
    Hi.  The page
    https://www.cdt.org/pr_statement/cdt-releases-new-report-origins-spam
    links to three pages under "Supporting Documents", all of which get
    "Page Not Found" errors:
   
      http://cdt.org/speech/spam/
      http://cdt.org/speech/spam/030319spamreport.shtml
      http://cdt.org/speech/spam/030319spamreport.pdf
   
    Can that spam report be restored to the CDT web site and the links fixed?
   
   Thank you,
   -Karl Fogel
** "Ask Slashdot: Where Do You Get (or Share) News About Open Source Projects?"
   http://developers.slashdot.org/story/14/07/26/2238223/ask-slashdot-where-do-you-get-or-share-news-about-open-source-projects?utm_source=rss1.0mainlinkanon&utm_medium=feed
** In Ch. 3, "Bug Tracker", maybe talk about how the bug tracker is
   as important to watch as the repository?
** In Ch. 6, many examples use rev IDs rather than commit IDs.
   The principle is the same either way, but will readers be thrown by
   the syntax?  Would be good to at least point out that "commit FOO"
   means the same thing, and that the details of the syntax are not as
   important as *having* a syntax.
* Web site and build infrastructure
** BUG: DocBook->PDF via FOP continually breaks, totally unmaintainable.
   Wow, I'm so tired of this.  In theory, DocBook is convertible to PDF.
   In practice, you need a team of NASA scientists to get it working.
   At least, the method used in 'lang-makefile' here, with Apache FOP,
   has never stayed working for more than a year at a time as far as I
   can remember.  http://www.dpawson.co.uk/docbook/tools.html has some
   alternatives; search for "Off the top of my head, I know of the
   following ways to transform DocBook XML into PDF, with open
   source/free/semi-free software".  See also
   http://www.scons.org/doc/HTML/scons-user.html#b-DocbookPdf,
   and http://lwn.net/Articles/661778/ re 'dblatex'.
** BUG: Why is the output="printed" conditional not working?
   For example, in Chapter 8 there is this conditional:
 
     (see <xref linkend="trademarks"/><phrase output="printed">
     in <xref linkend="legal"/></phrase>)
   
   and yet the HTML output produces (with links, of course) this...
 
     (see the section called “Trademarks” in Chapter 10, Licenses,
     Copyrights, and Patents),
 
   ...in en/forks.html.  What's up with that?
** BUG: compatibility links don't produce .html files.
   When id="mailing-lists" changed to id="message-forums" in ch03.xml,
   we left an <anchor id="mailing-lists" /> in place for compatibility.
   However, that still doesn't produce mailing-lists.html, which means
   a bunch of links out on the Net will suddenly become obsolete.
   Solution is to find all the compatibility anchors and generate .html
   files that do a 301 redirect to the new link.
** BUG: Why are we getting this warning on every commit:
   "Warning: post-commit hook failed (exit code 1) with no output."
** Explanation of POSS web site to ORM et al
   The online version has some properties that I'd like to maintain -- the
   most important is probably the human-readable anchor names, for example:
   
     http://producingoss.com/en/forks.html#forks-handling
   
   It's not just that they're human-readable, it's that they stay stable no
   matter how content moves around.  I could move the material about forks
   to a completely different chapter, but the URL would stay the same (and
   when someone went to it directly online, they would automatically be in
   the right chapter when they got there, whatever chapter it is).
   
   Out on the Net, people refer to particular parts of the book using those
   section & anchor names.  So I can't afford to break those.
