[[choosing-a-name]]
==== Choose a Good Name

Put yourself in the shoes of someone who's just heard about your
project, perhaps by having stumbled across it while searching for
software to solve some problem. The first thing they'll encounter is the
project's name.

A good name will not automatically make your project successful, and a
bad name will not doom it—well, a _really_ bad name probably could do
that, but we start from the assumption that no one here is actively
trying to make their project fail. However, a bad name can slow down
adoption of the project, either because people don't take it seriously,
or because they simply have trouble remembering it.

A good name:

* Gives some idea what the project does, or at least is related in an
obvious way, such that if one knows the name and knows what the project
does, the name will come quickly to mind thereafter.
* Is easy to remember. Here, there is no getting around the fact that
English has become the default language of the Internet: "easy to
remember" usually means "easy for someone who can read English to
remember." Names that are puns dependent on native-speaker
pronounciation, for example, will be opaque to the many non-native
English readers out there. If the pun is particularly compelling and
memorable, it may still be worth it; just keep in mind that many people
seeing the name will not hear it in their head the way a native speaker
would.
* Is not the same as some other project's name, and does not infringe on
any trademarks. This is just good manners, as well as good legal sense.
You don't want to create identity confusion. It's hard enough to keep
track of everything that's available on the Net already, without
different things having the same name.
+
The resources mentioned earlier in
<<look-around>> are useful in discovering
whether another project already has the name you're thinking of. For the
U.S., trademark searches are available at
http://www.uspto.gov/[uspto.gov].
* If possible, is available as a domain name in the .com, .net, and .org
top-level domains. You should pick one, probably .org, to advertise as
the official home site for the project; the other two should forward
there and are simply to prevent third parties from creating identity
confusion around the project's name. Even if you intend to host the
project at some other site (see
<<canned-hosting>>), you can still
register project-specific domains and forward them to the hosting site.
It helps users a lot to have a simple URL to remember.
* If possible, is available as a username on
https://twitter.com/[Twitter] and other microblog sites. See
<<own-the-name>> for more on
this and its relationship to the domain name.
