[[communications-channels]]
==== Communications Channels

Visitors usually want to know how to reach the human beings involved
with the project. Provide the addresses of mailing lists, chat rooms,
IRC channels (<<technical-infrastructure>>), and any other forums
where others involved with the software can be reached. Make it clear
that you and the other authors of the project are subscribed to these
mailing lists, so people see there's a way to give feedback that will
reach the developers. Your presence on the lists does not imply a
committment to answer all questions or implement all feature requests.
In the long run, probably only a fraction users will use the forums
anyway, but the others will be comforted to know that they _could_ if
they ever needed to.

In the early stages of a project, there's no need to have separate user
and developer forums. It's much better to have everyone involved with
the software talking together, in one "room." Among early adopters, the
distinction between developer and user is often fuzzy; to the extent
that the distinction can be made, the ratio of developers to users is
usually much higher in the early days of the project than later on.
While you can't assume that every early adopter is a programmer who
wants to hack on the software, you can assume that they are at least
interested in following development discussions and in getting a sense
of the project's direction.

As this chapter is only about getting a project started, it's enough
merely to say that these communications forums need to exist. Later, in
<<growth>> in <<communications>>, we'll examine where and
how to set up such forums, the ways in which they might need moderation
or other management, and how to separate user forums from developer
forums, when the time comes, without creating an unbridgeable gulf.
