[[development-status]]
==== Development Status

Visitors usually want to know how a project is doing. For new projects,
they want to know the gap between the project's promise and current
reality. For mature projects, they want to know how actively it is
maintained, how often it puts out new releases, how responsive it is
likely to be to bug reports, etc.

There are a couple of different avenues for providing answers to these
questions. One is to have a development status page, listing the
project's near-term goals and needs (for example, it might be looking
for developers with a particular kind of expertise). The page can also
give a history of past releases, with feature lists, so visitors can get
an idea of how the project defines "progress", and how quickly it makes
progress according to that definition. Some projects structure their
development status page as a roadmap that includes the future: past
events are shown on the dates they actually happened, future ones on the
approximate dates the project hopes they will happen.

The other way — not mutually exclusive with the first, and in fact
probably best done in combination with it — is to have various
automatically-maintained counters and indicators embedded in the
projects's front page and/or its developer landing page, showing various
pieces of information that, in the aggregate, give a sense of the
project's development status and progress. For example, an Announcements
or News panel showing recent news items, a Twitter or other microblog
stream showing notices that match the project's designated hashtags, a
timeline of recent releases, a panel showing recent activity in the bug
tracker (bugs filed, bugs responded to), another showing mailing list or
discussion forum activity, etc. Each such indicator should be a gateway
to further information of its type: for example, clicking on the "recent
bugs" panel should take one to the full bug tracker, or at least to an
expanded view into bug tracker activity.

Really, there are two slightly different meanings of "development
status" being conflated here. One is the formal sense: where does the
project stand in relation to its stated goals, and how fast is it making
progress. The other is less formal but just as useful: how active is
this project? Is stuff going on? Are there people here, getting things
done? Often that latter notion is what a visitor is most interested in.
Whether or not a project met its most recent milestone is sometimes not
as interesting as the more fundamental question of whether it has an
active community of developers around it.

The two notions of development status are, of course, related, and a
well-presented project shows both kinds. The information can be divided
between the project's front page (show enough there to give an overview
of both types of development status) and a more developer-oriented page.

One site that does a pretty good job of showing developer-oriented
status indicators is Launchpad.net. Launchpad.net is a bit unusual in
that it is both a primary hosting platform for some projects, and a
secondary, packaging-oriented site for others (or rather, for those
others it is the primary site for the "project" of getting that
particular program packaged for the Ubuntu GNU/Linux operating system,
which Launchpad was specifically designed to support). In either case, a
project's landing page on Launchpad shows a variety of
automatically-maintained status indicators that quickly give an idea of
where the project stands. While simply imitating a Launchpad page is
probably not a good idea — your own project should think carefully about
what its best development status indicators are — Launchpad project
pages do provide some good examples of the possibilities. Start from the
top of a project page there and scroll down:
https://launchpad.net/drizzle[launchpad.net/drizzle]. or
https://launchpad.net/inkscape[launchpad.net/inkscape], to pick two at
random.

[[development-status-honesty]]
===== Development status should always reflect reality.

Don't be afraid of looking unready, and never give in to the temptation
to inflate or hype the development status. Everyone knows that software
evolves by stages; there's no shame in saying "This is alpha software
with known bugs. It runs, and works at least some of the time, but use
at your own risk." Such language won't scare away the kinds of
developers you need at that stage. As for users, one of the worst things
a project can do is attract users before the software is ready for them.
A reputation for instability or bugginess is very hard to shake, once
acquired. Conservativism pays off in the long run; it's always better
for the software to be _more_ stable than the user expected than less,
and pleasant surprises produce the best kind of word-of-mouth.

The term alpha usually means a first release, with which users can get
real work done and which has all the intended functionality, but which
also has known bugs. The main purpose of alpha software is to generate
feedback, so the developers know what to work on. The next stage, beta,
means the software has had all the serious bugs fixed, but has not yet
been tested enough to certify for production release. The purpose of
beta software is to either become the official release, assuming no bugs
are found, or provide detailed feedback to the developers so they can
reach the official release quickly. The difference between alpha and
beta is very much a matter of judgement.
