[[developer-guidelines]]
==== Developer Guidelines

If someone is considering contributing to the project, she'll look for
developer guidelines. Developer guidelines are not so much technical as
social: they explain how the developers interact with each other and
with the users, and ultimately how things get done.

This topic is covered in detail in <<written-rules>> in
<<social-infrastructure>>, but the basic elements of developer
guidelines are:

* pointers to forums for interaction with other developers
* instructions on how to report bugs and submit patches
* some indication of _how_ development is usually done and how decisions
are made—is the project a benevolent dictatorship, a democracy, or
something else

No pejorative sense is intended by "dictatorship", by the way. It's
perfectly okay to run a tyranny where one particular developer has veto
power over all changes. Many successful projects work this way. The
important thing is that the project come right out and say so. A tyranny
pretending to be a democracy will turn people off; a tyranny that says
it's a tyranny will do fine as long as the tyrant is competent and
trusted. (See <<forkability>> in <<social-infrastructure>>
for why dictatorship in open source projects doesn't have the same
implications as dictatorship in other areas of life.)

http://subversion.apache.org/docs/community-guide/[subversion.apache.org/docs/community-guide]
is an example of particularly thorough developer guidelines; the
LibreOffice guidelines at
https://wiki.documentfoundation.org/Development[wiki.documentfoundation.org/Development]
are also a good example.

The separate issue of providing a programmer's introduction to the
software is discussed in
<<developer-documentation>> later in this
chapter.
