[[downloads]]
==== Downloads

The software should be downloadable as source code in standard formats.
When a project is first getting started, binary (executable) packages
are not necessary, unless the software has such complicated build
requirements or dependencies that merely getting it to run would be a
lot of work for most people. (But if this is the case, the project is
going to have a hard time attracting developers anyway!)

The distribution mechanism should be as convenient, standard, and
low-overhead as possible. If you were trying to eradicate a disease, you
wouldn't distribute the medicine in such a way that it requires a
non-standard syringe size to administer. Likewise, software should
conform to standard build and installation methods; the more it deviates
from the standards, the more potential users and developers will give up
and go away confused.

That sounds obvious, but many projects don't bother to standardize their
installation procedures until very late in the game, telling themselves
they can do it any time: _"We'll sort all that stuff out when the code
is closer to being ready."_ What they don't realize is that by putting
off the boring work of finishing the build and installation procedures,
they are actually making the code take longer to get ready—because they
discourage developers who might otherwise have contributed to the code,
if only they could build and test it. Most insidiously, the project
won't even _know_ it's losing all those developers, because the process
is an accumulation of non-events: someone visits a web site, downloads
the software, tries to build it, fails, gives up and goes away. Who will
ever know it happened, except the person themselves? No one working on
the project will realize that someone's interest and good will have been
silently squandered.

Boring work with a high payoff should always be done early, and
significantly lowering the project's barrier to entry through good
packaging brings a very high payoff.

When you release a downloadable package, give it a unique version
number, so that people can compare any two releases and know which
supersedes the other. That way they can report bugs against a particular
release (which helps respondents to figure out if the bug is already
fixed or not). A detailed discussion of version numbering can be found
in <<release-numbering>>, and the details of standardizing build
and installation procedures are covered in <<packaging>>, both in
<<development-cycle>>.
