[[examples-and-demos]]
==== Demos, Screenshots, Videos, and Example Output

If the project involves a graphical user interface, or if it produces
graphical or otherwise distinctive output, put some samples up on the
project web site. In the case of interface, this means screenshots or,
better yet, a brief (4 minutes or fewer) video with subtitles or a
narrator. For output, it might be screenshots or just sample files to
download. For web-based software, the gold standard is a demo site, of
course, assuming the software is amenable to that.

The main thing is to cater to people's desire for instant gratification
in the way they are most likely to expect. A single screenshot or video
can be more convincing than paragraphs of descriptive text and mailing
list chatter, because it is proof that the software __works__. The code
may still be buggy, it may be hard to install, it may be incompletely
documented, but image-based evidence shows people that if one puts in
enough effort, one can get it to run.

If you have a video demonstration of your project, keep the video under
4 minutes long, and make sure people can see the duration _before_ they
click on it. This is in keeping with the "principle of scaled
presentation" mentioned earlier: you want to make the decision to watch
the video an easy one, by removing all the risk. Visitors are more
likely to click on a link that says "Watch our 3 minute video" than on
one that just says "Watch our video", because in the former case they
know what they're getting into before they click — and they'll watch it
better, because they've mentally prepared the necessary amount of
commitment beforehand, and so won't tire mid-way through.

As to where the four-minute limit came from: it's a scientific fact,
determined through many attempts by the same experimental subject (who
shall remain unnamed) to watch project videos. The limit does not apply
to tutorials or other instructional material, of course; it's just for
introductory videos.

In case you don't already have preferred software for recording desktop
interaction videos: I've had good luck with `gtk-recordmydesktop` on
Debian GNU/Linux, and then the `OpenShot` video editor for post-capture
editing.

There are many other things you could put on the project web site, if
you have the time, or if for one reason or another they are especially
appropriate: a news page, a project history page, a related links page,
a site-search feature, a donations link, etc. None of these are
necessities at startup time, but keep them in mind for the future.
