[[features-and-requirements]]
==== Features and Requirements List

There should be a brief list of the features the software supports (if
something isn't completed yet, you can still list it, but put
"__planned__" or "__in progress__" next to it), and the kind of
computing environment required to run the software. Think of the
features/requirements list as what you would give to someone asking for
a quick summary of the software. It is often just a logical expansion of
the mission statement. For example, the mission statement might say:

___________________________________________________________________________________________________________________________________________________________
_To create a full-text indexer and search engine with a rich API, for
use by programmers in providing search services for large collections of
text files._
___________________________________________________________________________________________________________________________________________________________

The features and requirements list would give the details, clarifying
the mission statement's scope:

_______________________________________________________________________________
_Features:_

* _Searches plain text, HTML, and XML_
* _Word or phrase searching_
* _(planned) Fuzzy matching_
* _(planned) Incremental updating of indexes_
* _(planned) Indexing of remote web sites_

_Requirements:_

* _Python 2.2 or higher_
* _Enough disk space to hold the indexes (approximately 2x original data
size)_
_______________________________________________________________________________

With this information, readers can quickly get a feel for whether this
software has any hope of working for them, and they can consider getting
involved as developers too.
