[[hosting]]
==== Hosting

Where on the Internet should you put the project's materials?

A web site, obviously — but the full answer is a little more complicated
than that.

Many projects distinguish between their primary public user-facing web
site — the one with the pretty pictures and the "About" page and the
gentle introductions and videos and guided tours and all that
stuff — and their developers' site, where everything's grungy and full
of closely-spaced text in monospace fonts and impenetrable
abbreviations.

Well, I exaggerate. A bit. In any case, in the early stages of your
project it is not so important to distinguish between these two
audiences. Most of the interested visitors you get will be developers,
or at least people who are comfortable trying out new code. Over time,
you may find it makes sense to have a user-facing site (of course, if
your project is a code library, those "users" might be other
programmers) and a somewhat separate collaboration area for those
interested in participating in development. The collaboration site would
have the code repository, bug tracker, development wiki, links to
development mailing lists, etc. The two sites should link to each other,
and in particular it's important that the user-facing site make it clear
that the project is open source and where the open source development
activity can be found.footnote:[As of August 2013, a good example of a
project with separate but cross-linked primary and developer sites is
the Ozone Widget Framework: compare their main user-facing site at
http://www.ozoneplatform.org/[ozoneplatform.org] with their development
area at
https://github.com/ozoneplatform/owf[github.com/ozoneplatform/owf].]

In the past, many projects set up the developer site and infrastructure
themselves. Over the last decade or so, however, most open source
projects — and almost all the new ones — just use one of the "canned
hosting" sites that have sprung up to offer these services for free to
open source projects. By far the most popular such site, as of this
writing in mid-2013, is https://github.com/[GitHub.com], and if you
don't have a strong preference about where to host, you should probably
just choose GitHub; many developers are already familiar with it and
have personal accounts there. <<canned-hosting>> in
<<technical-infrastructure>> has a more detailed discussion of
the questions to consider when choosing a canned hosting site, and an
overview of the most popular ones.
