[[look-around]]
=== But First, Look Around

Before starting an open source project, there is one important caveat:

Always look around to see if there's an existing project that does what
you want. The chances are pretty good that whatever problem you want
solved now, someone else wanted solved before you. If they did solve it,
and released their code under a free license, then there's no reason for
you to reinvent the wheel today. There are exceptions, of course: if you
want to start a project as an educational experience, pre-existing code
won't help; or maybe the project you have in mind is so specialized that
you know there is zero chance anyone else has done it. But generally,
there's no point not looking, and the payoff can be huge. If the usual
Internet search engines don't turn up anything, try searching directly
on http://github.com/[github.com], http://ohloh.net/[ohloh.net],
http://freecode.com/[freecode.com],
http://code.google.com/[code.google.com],
http://www.sourceforge.net/[sourceforge.net], and in the Free Software
Foundation's directory of free software at
http://directory.fsf.org/[directory.fsf.org].

Even if you don't find exactly what you were looking for, you might find
something so close that it makes more sense to join that project and add
functionality than to start from scratch yourself.
