[[mission-statement]]
==== Have a Clear Mission Statement

Once they've found the project's home site, the next thing people will
look for is a quick description or mission statement, so they can decide
(within 30 seconds) whether or not they're interested in learning more.
This should be prominently placed on the front page, preferably right
under the project's name.

The description should be concrete, limiting, and above all, short.
Here's an example of a good one, from
http://hadoop.apache.org/[hadoop.apache.org]:

__________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________
_The Apache™ Hadoop® project develops open-source software for reliable,
scalable, distributed computing._

_The Apache Hadoop software library is a framework that allows for the
distributed processing of large data sets across clusters of computers
using simple programming models. It is designed to scale up from single
servers to thousands of machines, each offering local computation and
storage. Rather than rely on hardware to deliver high-availability, the
library itself is designed to detect and handle failures at the
application layer, so delivering a highly-available service on top of a
cluster of computers, each of which may be prone to failures._
__________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________

In just four sentences, they've hit all the high points, largely by
drawing on the reader's prior knowledge. That's an important point: it's
okay to assume a minimally informed reader with a baseline level of
preparedness. A reader who doesn't know what "clusters" and
"high-availability" mean in this context probably can't make much use of
Hadoop anyway, so there's no point writing for a reader who knows any
less than that. The phrase "designed to detect and handle failures at
the application layer" will stand out to engineers who have experience
with large-scale computing clusters—when they see those words, they'll
know that the people behind Hadoop understand that world, and will thus
be more willing to give Hadoop consideration.

Those who remain interested after reading the mission statement will
next want to see more details, perhaps some user or developer
documentation, and eventually will want to download something. But
before any of that, they'll need to be sure it's open source.
