[[own-the-name]]
===== Own the name in the important namespaces

For large projects, it is a good idea to own the project's name as many
of the relevant namespaces on the Internet as you can. By namespaces, I
mean not just the domain name system, but also online services in which
account names (usernames) are the publicly visible handle by which
people refer to the project. If you have the same name in all the places
where people would look for you, you make it easier for people to
sustain a mild interest in the project until they're ready to become
more involved.

For example, the Gnome free desktop project has the
http://gnome.org/[gnome.org] domain namefootnote:[They didn't manage to
get gnome.com or gnome.net, but that's okay — if you only have one, and
it's .org, it's fine. That's usually the first one people look for when
they're seeking the open source project of that name. If they couldn't
get "gnome.org" itself, a typical solution would be to get
"gnomeproject.org" instead, and many projects solve the problem that
way.], the https://twitter.com/gnome[@gnome] Twitter handle, the
https://identi.ca/gnome[gnome] username at
Identi.cafootnote:[https://identi.ca/[Identi.ca] is a microblog / social
networking that a number of free software developers use; its code is
open source and made available at http://pump.io/[pump.io]. For
developer-oriented projects, I recommend at least doing all status
microposts — colloquially referred to as "tweets" — on both Identi.ca
and Twitter. While the total number of people on Identi.ca is far
smaller than on Twitter, the percentage of them that are likely to be
interested in news about an open source project is far higher, at least
as of this writing in 2013 and for some years preceding that.], the
https://github.com/gnome[gnome] username at GitHub.comfootnote:[While
the master copy of Gnome's source code is at
http://git.gnome.org/[git.gnome.org], they maintain a mirror at GitHub,
since so many developers are already familiar with GitHub], and on the
freenode IRC network (see <<irc>>) they have the channel
`#gnome`, although they also maintain their own IRC servers (where they
control the channel namespace anyway, of course).

All this makes the Gnome project splendidly easy to find: it's usually
right where a potential contributor would expect it to be. Of course,
Gnome is a large and complex project with thousands of contributors and
many subdivisions; the advantage to Gnome of being easy to find is
greater than it would be for a newer project, since by now there are so
many ways to get involved in Gnome. But it will certainly never _harm_
your project to own its name in as many of the relevant namespaces as it
can, and it can sometimes help. So when you start a project, think about
what its online handle should be and register that handle with the
online services you think you're likely to care about. The ones
mentioned above are probably a good initial list, but you may know
others that are relevant for the particular subject area of your
project.
