[[state-freedom]]
==== State That the Project is Free

_The front page must make it unambiguously clear that the project is
open source._ This may seem obvious, but you would be surprised how many
projects forget to do it. I have seen free software project web sites
where the front page not only did not say which particular free license
the software was distributed under, but did not even state outright that
the software was free at all. Sometimes the crucial bit of information
was relegated to the Downloads page, or the Developers page, or some
other place that required one more mouse click to get to. In extreme
cases, the license was not given anywhere on the web site at all—the
only way to find it was to download the software and look at a license
file inside.

Please don't make this mistake. Such an omission can lose many potential
developers and users. State up front, right below the mission statement,
that the project is "free software" or "open source software", and give
the exact license. A quick guide to choosing a license is given in
<<license-quickstart>> later in
this chapter, and licensing issues are discussed in detail in
<<legal>>.

By this point, our hypothetical visitor has determined—probably in a
minute or less—that she's interested in spending, say, at least five
more minutes investigating this project. The next sections describe what
she should encounter in that five minutes.
