[[vc-and-bug-tracker-access]]
==== Version Control and Bug Tracker Access

Downloading source packages is fine for those who just want to install
and use the software, but it's not enough for those who want to debug or
add new features. Nightly source snapshots can help, but they're still
not fine-grained enough for a thriving development community. People
need real-time access to the latest sources, and a way to submit changes
based on those sources.

The solution is to use a version control system — specifically, an
online, publicly-accessible version controlled repository, from which
anyone can check out the project's materials and subsequently get
updates. A version control repository is a sign—to both users and
developers—that this project is making an effort to give people what
they need to participate. As of this writing, many open source projects
use https://github.com/[GitHub.com], which offers unlimited free public
version control hosting for open source projects. While GitHub is not
the only choice, nor even the only good choice, it's a reasonable one
for most projectsfootnote:[Although GitHub is based on Git, a popular
open source version control system, the code that runs GitHub's web
services is not itself open source. Whether this matters for your
project is a complex question, and is addressed in more depth in
<<canned-hosting>> in <<technical-infrastructure>>].
Version control infrastructure is discussed in detail in <<vc>> in
<<technical-infrastructure>>.

The same goes for the project's bug tracker. The importance of a bug
tracking system lies not only in its day-to-day usefulness to
developers, but in what it signifies for project observers. For many
people, an accessible bug database is one of the strongest signs that a
project should be taken seriously: the higher the number of bugs in the
database, the _better_ the project looks. This might seem
counterintuitive, but remember that the number of bug reports filed
really depends on three things: the absolute number of actual software
defects present in the code, the number of people using the software,
and the convenience with which those people can report new bugs. Of
these three factors, the latter two are much more significant than the
first. Any software of sufficient size and complexity has an essentially
arbitrary number of bugs waiting to be discovered. The real question is,
how well will the project do at recording and prioritizing those bugs? A
project with a large and well-maintained bug database (meaning bugs are
responded to promptly, duplicate bugs are unified, etc.) therefore makes
a better impression than a project with no bug database, or a nearly
empty database.

Of course, if your project is just getting started, then the bug
database will contain very few bugs, and there's not much you can do
about that. But if the status page emphasizes the project's youth, and
if people looking at the bug database can see that most filings have
taken place recently, they can extrapolate from that the project still
has a healthy _rate_ of filings, and they will not be unduly alarmed by
the low absolute number of bugs recorded.footnote:[For a more thorough
argument that bug reports should be treated as good news, see
http://www.rants.org/2010/01/10/bugs-users-and-tech-debt/[rants.org/2010/01/10/bugs-users-and-tech-debt],
an article I wrote in 2010 about how bug reports do _not_ represent
"http://en.wikipedia.org/wiki/Technical_debt[technical debt]" but rather
user engagement.]

Note that bug trackers are often used to track not only software bugs,
but enhancement requests, documentation changes, pending tasks, and
more. The details of running a bug tracker are covered in
<<bug-tracker>> in <<technical-infrastructure>>, so I won't
go into them here. The important thing from a presentation point of view
is just to _have_ a bug tracker, and to make sure that fact is visible
from the front page of the project.
